import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import WorkInProgressBanner from "./components/common/WorkInProgressBanner";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({ weight: ["400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextTopLoader /> <WorkInProgressBanner />
        {children}
      </body>
    </html>
  );
}
