/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevLogsIndexRouteImport } from './routes/dev-logs/index'
import { Route as DevLogsSlugRouteImport } from './routes/dev-logs/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogsIndexRoute = DevLogsIndexRouteImport.update({
  id: '/dev-logs/',
  path: '/dev-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogsSlugRoute = DevLogsSlugRouteImport.update({
  id: '/dev-logs/$slug',
  path: '/dev-logs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-logs/$slug': typeof DevLogsSlugRoute
  '/dev-logs/': typeof DevLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-logs/$slug': typeof DevLogsSlugRoute
  '/dev-logs': typeof DevLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-logs/$slug': typeof DevLogsSlugRoute
  '/dev-logs/': typeof DevLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev-logs/$slug' | '/dev-logs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev-logs/$slug' | '/dev-logs'
  id: '__root__' | '/' | '/dev-logs/$slug' | '/dev-logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevLogsSlugRoute: typeof DevLogsSlugRoute
  DevLogsIndexRoute: typeof DevLogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-logs/': {
      id: '/dev-logs/'
      path: '/dev-logs'
      fullPath: '/dev-logs/'
      preLoaderRoute: typeof DevLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-logs/$slug': {
      id: '/dev-logs/$slug'
      path: '/dev-logs/$slug'
      fullPath: '/dev-logs/$slug'
      preLoaderRoute: typeof DevLogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevLogsSlugRoute: DevLogsSlugRoute,
  DevLogsIndexRoute: DevLogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
